/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Section = IDL.Record({
  'score' : IDL.Nat,
  'notes' : IDL.Text,
  'checkedItems' : IDL.Vec(IDL.Bool),
});
export const Scorecard = IDL.Record({
  'vin' : IDL.Text,
  'status' : IDL.Text,
  'signature' : IDL.Text,
  'thermalCheck' : Section,
  'technicianName' : IDL.Text,
  'customerIssue' : Section,
  'electricalHealth' : Section,
  'date' : IDL.Text,
  'repairQuality' : Section,
  'safetyCheck' : Section,
  'redFlags' : IDL.Vec(IDL.Text),
  'totalScore' : IDL.Nat,
  'bmsDiagnostics' : Section,
  'visualInspection' : Section,
  'finalPerformance' : Section,
  'vehicleId' : IDL.Text,
});

export const idlService = IDL.Service({
  'createScorecard' : IDL.Func([Scorecard], [IDL.Nat], []),
  'deleteScorecard' : IDL.Func([IDL.Nat], [], []),
  'getAllScorecards' : IDL.Func([], [IDL.Vec(Scorecard)], ['query']),
  'getScorecard' : IDL.Func([IDL.Nat], [Scorecard], ['query']),
  'updateScorecard' : IDL.Func([IDL.Nat, Scorecard], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Section = IDL.Record({
    'score' : IDL.Nat,
    'notes' : IDL.Text,
    'checkedItems' : IDL.Vec(IDL.Bool),
  });
  const Scorecard = IDL.Record({
    'vin' : IDL.Text,
    'status' : IDL.Text,
    'signature' : IDL.Text,
    'thermalCheck' : Section,
    'technicianName' : IDL.Text,
    'customerIssue' : Section,
    'electricalHealth' : Section,
    'date' : IDL.Text,
    'repairQuality' : Section,
    'safetyCheck' : Section,
    'redFlags' : IDL.Vec(IDL.Text),
    'totalScore' : IDL.Nat,
    'bmsDiagnostics' : Section,
    'visualInspection' : Section,
    'finalPerformance' : Section,
    'vehicleId' : IDL.Text,
  });
  
  return IDL.Service({
    'createScorecard' : IDL.Func([Scorecard], [IDL.Nat], []),
    'deleteScorecard' : IDL.Func([IDL.Nat], [], []),
    'getAllScorecards' : IDL.Func([], [IDL.Vec(Scorecard)], ['query']),
    'getScorecard' : IDL.Func([IDL.Nat], [Scorecard], ['query']),
    'updateScorecard' : IDL.Func([IDL.Nat, Scorecard], [], []),
  });
};

export const init = ({ IDL }) => { return []; };