/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Scorecard {
  'vin' : string,
  'status' : string,
  'signature' : string,
  'thermalCheck' : Section,
  'technicianName' : string,
  'customerIssue' : Section,
  'electricalHealth' : Section,
  'date' : string,
  'repairQuality' : Section,
  'safetyCheck' : Section,
  'redFlags' : Array<string>,
  'totalScore' : bigint,
  'bmsDiagnostics' : Section,
  'visualInspection' : Section,
  'finalPerformance' : Section,
  'vehicleId' : string,
}
export interface Section {
  'score' : bigint,
  'notes' : string,
  'checkedItems' : Array<boolean>,
}
export interface _SERVICE {
  'createScorecard' : ActorMethod<[Scorecard], bigint>,
  'deleteScorecard' : ActorMethod<[bigint], undefined>,
  'getAllScorecards' : ActorMethod<[], Array<Scorecard>>,
  'getScorecard' : ActorMethod<[bigint], Scorecard>,
  'updateScorecard' : ActorMethod<[bigint, Scorecard], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];